# Generated by Django 4.1 on 2022-08-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
