# Generated by Django 4.1 on 2022-08-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
