# Generated by Django 4.1 on 2022-08-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
